---
# This role downloads AMQ7
- name: Download AMQ7 and Create Symlink
  hosts: all
  vars:
   group: jboss
   username: jboss
   user_pswd: Admin1234!
   user_home: /usr/local/jboss
   rh_username: matthew.hughes@axcelinno.io
   rh_password: Mr93ae96
   jboss_fuse_artifact_url: https://jbossproductsaps.s3.amazonaws.com/amq-broker-7.2.3-bin.zip
   symlink_name: AMQ7
   version: '7.2.3'

  tasks:
    - name: Download Jboss AMQ7 from S3 bucket -- (will change to Artifacrory)
      get_url: 
        url: "{{ jboss_fuse_artifact_url }}" #Register this as a variable
        dest: "{{ user_home }}"
      register: archive
    - debug:
        var=archive

    - name: Unarchive (EXTRACT) Jboss Fuse
      become: true
      unarchive:
        src: "{{ archive.dest }}"
        dest: "{{ user_home }}"
        copy: no
        owner: "{{ username }}"
        group: "{{ group }}"

    - name: Create Symbolic Link
      file:
        src: '{{ user_home }}/amq-broker-{{ version }}'
        dest: '{{ user_home }}/{{ symlink_name }}'
        state: link
