---
- name: ELK BEAT
  hosts: all
  tasks:
  
  - name: Download Filebeat RPM
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.2-x86_64.rpm
      dest: /opt/
    register: out
  - debug: var=out
  
  - name: Unarchive
    become: true
    shell: rpm -vi "{{ out.dest }}"
    args:
      chdir: /opt/
