---
- name: ELK BEAT
  hosts: all
  tasks:
  
  - name: Download Filebeat RPM
    get_url:
      url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.2-linux-x86_64.tar.gz
      dest: /opt/
    register: out
  - debug: var=out
  
  - name: Unarchive
    become: true
    shell: tar xzvf "{{ out.dest }}"
    args:
      chdir: /opt/
      
 # - name: Copy config file over
  
  - name: Start File Beat
    become: true
    shell: chown root filebeat.yml 
    args:
      chdir: /etc/filebeat/
    
  - name: Start command
    become: true
    shell: /filebeat -e
    args:
      chdir: /usr/share/bin
  
        
      
