---
- name: Testing
  hosts: all
  vars:
    PROCESS: Artemis
  
  tasks:
  
    - name: Graceful shutdown of AMQ
      shell: /usr/local/jboss/{{ broker_name }}/bin/artemis stop
    - pause:
        seconds: 30
   
   
    #- name: Graceful shutdown of FUSE
      #shell: /usr/local/jboss/{{ Fuse }}/
    
    - name: Check the process status
      shell: jps
      register: output
    - debug:
        var=output
  
    - name: Get running processes
      shell: "ps -ef | grep -v grep | grep -w {{ PROCESS }} | awk '{print $2}'"
      register: running_processes
      
    - debug:
        var=running_processes
        
    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"
 
    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: yes
      register: crunchify_processes
      
    - debug:
        var=crunchify_processes
    
###########################################
    - name: Create vg001
      lvg:
        vg: vg001
        pvs: /dev/sdb
    
    - name: Create LVM
      lvol:
        vg: vg001
        lv: lv001_001
        size: +100%FREE
        pvs: /dev/sdb
        
    - name: Create the filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg001/lv001_001
        opts: "-L /tmpmount/"
        
    - name: Mount the file system
      mount: 
        path: /tmpmount/
        src: /dev/vg001/lv001_001
        fstype: xfs
        state: mounted
#######################################################        
    - name: Copy contents over
      shell: find /usr/local/jboss/ -depth -print | cpio -pamVd /tmpmount/
      
    - name: Move the usr/local/jboss content to /tmp/
      shell: mv -r /usr/local/jboss /tmp/
   
    - name: Unmount
      mount:
        path: /tmpmount/
        state: unmounted #absent will remove mounts entry from /etc/fstab and will also unmount the device and remove the mount point
    
    - name: Rename /tmpmount/ in fstab
      mount:
        path: /usr/local/jboss/
        src: /dev/vg001/lv001_001
        fstype: xfs
        state: present
        
    - name: Mount
      mount:
        path: /usr/local/jboss
        src: /dev/vg001/lv001_001
        fstype: xfs
        state: mounted
