---
- name: Fuse Install Playbook
  hosts: all
  vars:
    jboss_group: jboss
    username: jboss
    user_pswd: Admin1234!
    user_home: /usr/local/jboss


  tasks:
    - name: Create the Jboss Fuse Group
      group:
        name: "{{ jboss_group }}"
        system: yes
        state: present
        gid: "400"
      tags:
        - jboss_fuse
    
    - name: Add user
      user:
        name: "{{ username }}"
        comment: "Jboss User"
        password: "{{ '{{ user_pswd }}' | password_hash('sha512') }}"
        create_home: true
        home: "{{ user_home }}"
    - name: Defensive Programming to check if FUSE already isntalled... Check existence of Libraries
      become: true
      stat:
        path: "{{ user_home + '/jboss-fuse6.2.1.redhat-084/etc/org.apache.karaf.features.cfg'}}"
      register: jboss_fuse_exists
      tags:
        - jboss_fuse
