---
- name: Fuse Install Playbook
  hosts: all
  vars:
    jboss_group: jboss
    username: jboss
    user_pswd: Admin1234!
    user_home: /usr/local/jboss


  tasks:
    - name: Create the Jboss Fuse Group
      group:
        name: "{{ jboss_group }}"
        system: yes
        state: present
        gid: "400"
      tags:
        - jboss_fuse
    
    - name: Add user
      user:
        name: "{{ username }}"
        comment: "Jboss User"
        password: "{{ '{{ user_pswd }}' | password_hash('sha512') }}"
        create_home: true
        home: "{{ user_home }}"
    - name: Create Library Destination
      become: true
      file:
        path: "{{ user_home }}"
        owner: "{{ username }}"
        group: " {{ jboss_group }}"
        state: directory
        mode: '755'
      tags:
        - jboss_fuse
