---
- name: Fuse Install Playbook
  hosts: all
  vars:
    jboss_group: jboss
    username: jboss
    user_pswd: Admin1234!
    user_home: /usr/local/jboss


  tasks:
    - name: Create the Jboss Fuse Group
      group:
        name: "{{ jboss_group }}"
        system: yes
        state: present
        gid: "400"
      tags:
        - jboss_fuse
    
    - name: Add user
      user:
        name: "{{ username }}"
        comment: "Jboss User"
        password: "{{ '{{ user_pswd }}' | password_hash('sha512') }}"
        create_home: true
        home: "{{ user_home }}"
    - name: Defensive Programming to check if FUSE already isntalled... Check existence of Libraries
      become: true
      stat:
        path: "{{ user_home + '/jboss-fuse6.2.1.redhat-084/etc/org.apache.karaf.features.cfg'}}"
      register: jboss_fuse_exists
      tags:
        - jboss_fuse
        
    - name: Install Java and Maven
      yum:
        name: "{{ packages }}"
        state: installed
      vars:
        packages:
        - java-1.8.0-openjdk
        - maven
    - name: Adding the path in the Profile files
      lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'> line="export JAVA_HOME=/usr/lib/jvm/java/"
    
    - name: Set M2_HOME var
      lineinfile: dest=~/.bashrc regexp='^M2_HOME'> line="export M2_HOME=/usr/share/maven"

    - name: Set M2 var
      lineinfile: dest=~/.bashrc regexp='^M2'> line="export M2=$M2_HOME/bin"  

    - name: Set JAVA_PATH
      lineinfile: dest=~/.bashrc regexp='^JAVA_HOME'> line="export PATH=$M2:$PATH"

    - name: Source Bashrc
      action: shell source ~/.bashrc  
      
    - name: Echo JAVA_HOME
      shell: "echo $JAVA_HOME"
