---
- name: LPAR2RRD
  hosts: all
  tasks:

    - name: Download LPAR2RRD agent
      get_url:
        url: https://www.lpar2rrd.com/agent/lpar2rrd-agent-6.10-0.noarch.rpm
        dest: /opt/
      register: output
    - debug: var=output
    
    


   # - name: Installation
     # shell: rpm -Uvh "{{ output.dest }}"
     # args:
       # chdir: /opt/

    - name: Shell
      shell: rpm -qa|grep lpar2rrd-agent
      register: test
    - debug: var=test
    
   # - name: Touch again the same file, but dont change times this makes the task idempotent
      #file:
        #path: /var/spool/cron/mrh
        #state: touch
    

    - name: Crontab
      shell: echo "* * * * * /usr/bin/perl /opt/lpar2rrd-agent/lpar2rrd-agent.pl 10.10.158.11 > /var/tmp/lpar2rrd-agent.out 2>&1" >> /var/spool/cron/mrh
