---
- name: LPAR2RRD
  hosts: all
  tasks:

    - name: Download LPAR2RRD agent
      get_url:
        url: https://www.lpar2rrd.com/agent/lpar2rrd-agent-6.10-0.noarch.rpm
        dest: /opt/
      register: output
    - debug: var=output

    - name: Installation
      shell: sudo rpm -Uvh "{{ output.dest }}"
      #args:
       # chdir: /opt/

    - name: Shell
      shell: rpm -qa|grep lpar2rrd-agent

    - name: Crontab
      shell: ehco "* * * * * /usr/bin/perl /opt/lpar2rrd-agent/lpar2rrd-agent.pl 10.10.158.11 > /var/tmp/lpar2rrd-agent.out 2>&1" >> /var/spool/cron/mrh
