---
- name: Testing
  hosts: all
  vars:
    PROCESS: java
    broker_name: amq-broker1
  
  tasks:
  
    - name: Graceful shutdown of AMQ
      shell: /usr/local/jboss/{{ broker_name }}/bin/artemis stop
      
    - name: wait
      wait_for:
        timeout: 15
   
   
    #- name: Graceful shutdown of FUSE
      #shell: ./usr/local/jboss/fuse/bin/stop 
    
    - name: Check the process status
      shell: jps
      register: output
    - debug:
        var=output
  
    - name: Get running processes
      shell: "ps -ef | grep -v grep | grep -w {{ PROCESS }} | awk '{print $2}'"
      register: running_processes
      
    - debug:
        var=running_processes
        
    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_processes.stdout_lines }}"
 
    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: yes
      register: fuse_processes
      
    - debug:
        var=fuse_processes
        
    - name: PAUSE FOR VERIFICATION
      pause:
      echo: yes
        
    - name: Create vg001
      lvg:
        vg: vg001
        pvs: /dev/sdb
    
    - name: Create LVM
      lvol:
        vg: vg001
        lv: lv001_001
        size: +100%FREE
        pvs: /dev/sdb
        
    - name: Create the filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg001/lv001_001
        opts: "-L /tmpmount/"
        
    - name: Mount the file system
      mount: 
        path: /tmpmount/
        src: /dev/vg001/lv001_001
        fstype: xfs
        state: mounted
