---
- name: Testing
  hosts: all
  
  tasks:
    - name: Check the process status
      shell: jps
      register: output
    - debug:
        var=output
  
  
    - name: Get running processes
      shell: "ps -ef | grep -v grep | grep -w {{ PROCESS }} | awk '{print $2}'"
      register: running_processes
      
    - debug:
        var=running_processes
      
