---
- name: Testing
- hosts: all
  gather_facts: no
  become: true
  
  tasks:
    - name Check the process status
      shell: ps -ef | grep java
      register: output
    - debug:
        var=output
      
  
