---
# This role executes the neccessary pre-reqs for installing either AMQ7 or FUSE
#This role will do the following:
#     - Create jboss user and group
#     - Install OpenJDK
#     - Install Maven
#     - Set environment a variables

- name: Jboss_PreReq Role
  hosts: all
  vars: 
    group: jboss
    pswd: "Admin1234!"
    username: jboss
    user_home: /usr/local/jboss
    maven_home_parent_directory: /usr/share
    maven: maven
    java_home_parent_directory: /usr/lib/jvm/
    
  tasks:
    - name: Create group jboss
      group:
        name: "{{ group }}"
        system: yes
        state: present
        gid: "400" # CHECK THIS VALUE
      tags:
        - jboss_fuse
      
    - name: Create user and users home directory
      user: 
        name: "{{ username }}"
        comment: "'{{ username }}' user"
        password: "{{  '{{ pswd }}' | password_hash('sha512') }}"
        create_home: true
        home: "{{ user_home }}"

    - name: Install OpenJDK and Maven Packages
      yum:
        name: "{{ packages }}"
        state: installed
      vars:
        packages:
        - java-1.8.0-openjdk
        - maven
      register: output
    - debug:
        var=output
        
        
    #Consider moving these into a jinja2 template
    - name: Maven Path Configuration
      lineinfile:
        dest: /etc/profile.d/maven.sh
        line: '{{item.line }}'
        create: yes
        state: present
      with_items:
        - { line: 'M2_HOME={{ maven_home_parent_directory }}/{{ maven }}' }
        - { line: 'PATH=$PATH:$M2_HOME/bin' }
      register: mavenVar
    
    - debug:
        var=mavenVar
        
    - name: Java Path configuration
      lineinfile:
        dest: /etc/profile.d/java.sh
        line: '{{ item.line }}'
        create: yes
        state: present
      with_items:
        - { line: 'JAVA_HOME={{ java_home_parent_directory }}/java' }
        
