---
##### This role installs AMQ7 #####
# The variables are set under vars directory                 #
# Change the url to point to the FUSE archive in artifactory #


- name: Download Jboss AMQ7 from S3 bucket -- (will change to Artifacrory)
  get_url: 
    url: "{{ jboss_fuse_artifact_url }}"
    dest: "{{ user_home }}"
  register: archive
- debug:
    var=archive

- name: Unarchive (EXTRACT) Jboss Fuse
  become: true
  unarchive:
    src: "{{ archive.dest }}"
    dest: "{{ user_home }}"
    copy: no
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Create Symbolic Link
  file:
    src: '{{ user_home }}/amq-broker-{{ version }}'
    dest: '{{ user_home }}/{{ symlink_name }}'
    state: link
